/**
 * Campaign Configuration Dictionary
 * 
 * Provides:
 * 1. Available Merge Tags organized by category with labels and mock values for previews.
 * 2. Supported System Trigger Events with allowed context variables.
 */

const MERGE_TAGS = [
  // User & Account Tags
  {
    category: "User & Account",
    tag: "{{username}}",
    label: "Username",
    description: "User's login username or email handle",
    sampleValue: "john_doe",
  },
  {
    category: "User & Account",
    tag: "{{first_name}}",
    label: "First Name",
    description: "Recipient's first name",
    sampleValue: "John",
  },
  {
    category: "User & Account",
    tag: "{{last_name}}",
    label: "Last Name",
    description: "Recipient's last name",
    sampleValue: "Doe",
  },
  {
    category: "User & Account",
    tag: "{{user_email}}",
    label: "User Email",
    description: "Recipient's registered email address",
    sampleValue: "john.doe@example.com",
  },
  {
    category: "User & Account",
    tag: "{{user_phone}}",
    label: "Phone Number",
    description: "Recipient's registered phone number",
    sampleValue: "+91 9876543210",
  },
  {
    category: "User & Account",
    tag: "{{reset_link}}",
    label: "Password Reset Link",
    description: "Secure password reset URL link",
    sampleValue: "https://anevix.com/reset-password?token=example_token_123",
  },
  {
    category: "User & Account",
    tag: "{{verification_otp}}",
    label: "Verification OTP",
    description: "One-time password for email/account verification",
    sampleValue: "582914",
  },
  {
    category: "User & Account",
    tag: "{{temporary_password}}",
    label: "Temporary Password",
    description: "Temporary password generated by admin for new accounts",
    sampleValue: "Temp#Pass2026",
  },
  {
    category: "User & Account",
    tag: "{{login_url}}",
    label: "Login URL",
    description: "Direct link to customer or seller login portal",
    sampleValue: "https://anevix.com/login",
  },

  // Order Tags
  {
    category: "Order Details",
    tag: "{{order_id}}",
    label: "Order ID",
    description: "Unique order reference number",
    sampleValue: "ORD-948210",
  },
  {
    category: "Order Details",
    tag: "{{order_status}}",
    label: "Order Status",
    description: "Current order fulfillment or payment status",
    sampleValue: "Shipped",
  },
  {
    category: "Order Details",
    tag: "{{order_total}}",
    label: "Order Total Amount",
    description: "Total payable or paid amount for the order",
    sampleValue: "2,499.00",
  },
  {
    category: "Order Details",
    tag: "{{currency}}",
    label: "Currency",
    description: "Currency code (e.g. INR, USD)",
    sampleValue: "INR",
  },
  {
    category: "Order Details",
    tag: "{{payment_method}}",
    label: "Payment Method",
    description: "Mode of payment (Card, UPI, COD, etc.)",
    sampleValue: "UPI / Net Banking",
  },
  {
    category: "Order Details",
    tag: "{{tracking_number}}",
    label: "Tracking Number",
    description: "Shipment AWB / Tracking identifier",
    sampleValue: "AWB783921004IN",
  },
  {
    category: "Order Details",
    tag: "{{tracking_url}}",
    label: "Tracking URL",
    description: "Direct courier tracking link",
    sampleValue: "https://track.courier.com/AWB783921004IN",
  },
  {
    category: "Order Details",
    tag: "{{shipping_address}}",
    label: "Shipping Address",
    description: "Delivery street address, city, and pincode",
    sampleValue: "Flat 402, Sunshine Heights, Mumbai - 400001",
  },
  {
    category: "Order Details",
    tag: "{{items_summary}}",
    label: "Order Items Summary",
    description: "Formatted list or summary of ordered products",
    sampleValue: "1x Wireless Headphones (Black), 2x USB-C Fast Charger",
  },

  // Seller Tags
  {
    category: "Seller & Business",
    tag: "{{store_name}}",
    label: "Store / Business Name",
    description: "Registered trade or business name of the seller",
    sampleValue: "Apex Electronics Hub",
  },
  {
    category: "Seller & Business",
    tag: "{{seller_name}}",
    label: "Seller Contact Name",
    description: "Full name of the authorized seller representative",
    sampleValue: "Vikram Sharma",
  },
  {
    category: "Seller & Business",
    tag: "{{seller_email}}",
    label: "Seller Email",
    description: "Official business email address",
    sampleValue: "vikram@apexelectronics.in",
  },
  {
    category: "Seller & Business",
    tag: "{{pan_number}}",
    label: "PAN Number",
    description: "Masked or verified business PAN",
    sampleValue: "ABCDE1234F",
  },
  {
    category: "Seller & Business",
    tag: "{{gstin_number}}",
    label: "GSTIN Number",
    description: "Goods and Services Tax Identification Number",
    sampleValue: "27ABCDE1234F1Z5",
  },
  {
    category: "Seller & Business",
    tag: "{{onboarding_step}}",
    label: "Current Onboarding Step",
    description: "The stage of the seller onboarding process",
    sampleValue: "Bank Verification",
  },
  {
    category: "Seller & Business",
    tag: "{{rejection_reason}}",
    label: "Rejection Reason",
    description: "Explanation notes provided when rejecting a seller profile or product",
    sampleValue: "GSTIN certificate document is blurred. Please re-upload a clear scanned copy.",
  },
  {
    category: "Seller & Business",
    tag: "{{reapplication_link}}",
    label: "Re-application Link",
    description: "Direct link for rejected sellers to update documents and re-apply",
    sampleValue: "https://anevix.com/seller/onboarding/reapply",
  },

  // Support & Ticket Tags
  {
    category: "Support & Helpdesk",
    tag: "{{ticket_id}}",
    label: "Ticket ID",
    description: "Support ticket ticket number",
    sampleValue: "TCK-4819",
  },
  {
    category: "Support & Helpdesk",
    tag: "{{ticket_subject}}",
    label: "Ticket Subject",
    description: "Title of the support issue or query",
    sampleValue: "Delivery delayed for Order #ORD-948210",
  },
  {
    category: "Support & Helpdesk",
    tag: "{{ticket_priority}}",
    label: "Ticket Priority",
    description: "Priority of the ticket (Low, Medium, High, Urgent)",
    sampleValue: "High",
  },
  {
    category: "Support & Helpdesk",
    tag: "{{ticket_status}}",
    label: "Ticket Status",
    description: "Status of the ticket (Open, In Progress, Resolved, Closed)",
    sampleValue: "Resolved",
  },
  {
    category: "Support & Helpdesk",
    tag: "{{ticket_resolution}}",
    label: "Resolution Summary",
    description: "Support agent's resolution remarks or notes",
    sampleValue: "Shipment rerouted with express delivery. Delivered successfully.",
  },

  // Company & System Defaults
  {
    category: "General & Branding",
    tag: "{{company_name}}",
    label: "Company / App Name",
    description: "Official marketplace brand name",
    sampleValue: "Anevix Ecommerce",
  },
  {
    category: "General & Branding",
    tag: "{{support_email}}",
    label: "Support Email",
    description: "Default customer care email",
    sampleValue: "support@anevix.com",
  },
  {
    category: "General & Branding",
    tag: "{{site_url}}",
    label: "Website URL",
    description: "Main website homepage link",
    sampleValue: "https://anevix.com",
  },
  {
    category: "General & Branding",
    tag: "{{current_year}}",
    label: "Current Year",
    description: "Current calendar year for copyright footers",
    sampleValue: new Date().getFullYear().toString(),
  },
];

const TRIGGER_EVENTS = [
  // User & Account Events
  {
    id: "USER_REGISTRATION",
    name: "User Registration",
    category: "User & Account",
    description: "Triggered immediately after a new user completes initial signup.",
    applicableTags: ["username", "first_name", "last_name", "user_email", "verification_otp", "company_name", "site_url"],
  },
  {
    id: "WELCOME_USER",
    name: "Welcome User",
    category: "User & Account",
    description: "Triggered when an account is verified and ready for browsing/shopping.",
    applicableTags: ["username", "first_name", "last_name", "user_email", "login_url", "company_name", "site_url"],
  },
  {
    id: "FORGOT_PASSWORD",
    name: "Forgot Password",
    category: "User & Account",
    description: "Triggered when a user requests a password reset link.",
    applicableTags: ["username", "first_name", "reset_link", "support_email", "company_name"],
  },
  {
    id: "USER_ADDED",
    name: "User Added (By Admin)",
    category: "User & Account",
    description: "Triggered when an administrator manually creates an account for a user.",
    applicableTags: ["username", "first_name", "last_name", "user_email", "temporary_password", "login_url", "company_name"],
  },
  {
    id: "USER_UPDATED",
    name: "User Updated",
    category: "User & Account",
    description: "Triggered when account profile details (email, phone, name) are modified.",
    applicableTags: ["username", "first_name", "last_name", "user_email", "company_name"],
  },
  {
    id: "PASSWORD_CHANGED",
    name: "Password Changed",
    category: "User & Account",
    description: "Security notice triggered immediately after a password is changed.",
    applicableTags: ["username", "first_name", "user_email", "support_email", "company_name"],
  },

  // Order Events
  {
    id: "ORDER_PURCHASED",
    name: "Order Purchased",
    category: "Order Events",
    description: "Triggered when customer successfully places and pays for an order.",
    applicableTags: ["username", "first_name", "order_id", "order_total", "currency", "payment_method", "shipping_address", "items_summary", "company_name"],
  },
  {
    id: "ORDER_FAILED",
    name: "Order Failed",
    category: "Order Events",
    description: "Triggered when a payment or order placement fails.",
    applicableTags: ["username", "first_name", "order_id", "order_total", "currency", "support_email", "company_name"],
  },
  {
    id: "ORDER_SHIPPED",
    name: "Order Shipped",
    category: "Order Events",
    description: "Triggered when shipment tracking information is generated.",
    applicableTags: ["username", "first_name", "order_id", "tracking_number", "tracking_url", "shipping_address", "company_name"],
  },
  {
    id: "ORDER_DELIVERED",
    name: "Order Delivered",
    category: "Order Events",
    description: "Triggered when courier marks shipment as successfully delivered.",
    applicableTags: ["username", "first_name", "order_id", "shipping_address", "company_name", "support_email"],
  },

  // Seller Events
  {
    id: "SELLER_REGISTRATION",
    name: "New Seller Registration",
    category: "Seller Events",
    description: "Triggered when a vendor registers for business onboarding.",
    applicableTags: ["seller_name", "seller_email", "store_name", "onboarding_step", "company_name"],
  },
  {
    id: "SELLER_ONBOARDING_COMPLETED",
    name: "Onboarding Successfully Completed",
    category: "Seller Events",
    description: "Triggered when seller finishes submitting PAN, GSTIN, and Bank details for review.",
    applicableTags: ["seller_name", "seller_email", "store_name", "company_name", "support_email"],
  },
  {
    id: "SELLER_ACCOUNT_APPROVED",
    name: "Account Approved",
    category: "Seller Events",
    description: "Triggered when an admin reviews and approves the seller's storefront.",
    applicableTags: ["seller_name", "seller_email", "store_name", "login_url", "company_name"],
  },
  {
    id: "SELLER_ACCOUNT_REJECTED",
    name: "Account Rejected",
    category: "Seller Events",
    description: "Triggered when admin rejects the seller application with rejection notes.",
    applicableTags: ["seller_name", "seller_email", "store_name", "rejection_reason", "reapplication_link", "support_email", "company_name"],
  },
  {
    id: "SELLER_ACCOUNT_REAPPLICATION",
    name: "Account Re-application",
    category: "Seller Events",
    description: "Triggered when a previously rejected seller resubmits their profile.",
    applicableTags: ["seller_name", "seller_email", "store_name", "company_name"],
  },

  // Support / Ticket Events
  {
    id: "TICKET_RAISED",
    name: "Ticket Raised",
    category: "Support & Helpdesk",
    description: "Triggered when customer or seller creates a new help ticket.",
    applicableTags: ["username", "first_name", "ticket_id", "ticket_subject", "ticket_priority", "ticket_status", "company_name"],
  },
  {
    id: "TICKET_RESOLVED",
    name: "Ticket Resolved",
    category: "Support & Helpdesk",
    description: "Triggered when a support representative marks an inquiry as solved.",
    applicableTags: ["username", "first_name", "ticket_id", "ticket_subject", "ticket_resolution", "company_name", "support_email"],
  },
];

const getSampleContext = () => {
  const sample = {};
  MERGE_TAGS.forEach((item) => {
    // Strip {{ and }}
    const cleanKey = item.tag.replace(/^\{\{\s*|\s*\}\}$/g, "");
    sample[cleanKey] = item.sampleValue;
  });
  return sample;
};

module.exports = {
  MERGE_TAGS,
  TRIGGER_EVENTS,
  getSampleContext,
};
